/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DataPopupRouteImport } from './routes/data-popup'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppUsersRouteImport } from './routes/_app.users'
import { Route as AppUsageRouteImport } from './routes/_app.usage'
import { Route as AppScheduleViewRouteImport } from './routes/_app.schedule-view'
import { Route as AppScheduleRouteImport } from './routes/_app.schedule'
import { Route as AppSamplesRouteImport } from './routes/_app.samples'
import { Route as AppMethodsRouteImport } from './routes/_app.methods'
import { Route as AppInventoryRouteImport } from './routes/_app.inventory'
import { Route as AppImportsRouteImport } from './routes/_app.imports'
import { Route as AppDataRouteImport } from './routes/_app.data'
import { Route as AppAnalyticsRouteImport } from './routes/_app.analytics'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DataPopupRoute = DataPopupRouteImport.update({
  id: '/data-popup',
  path: '/data-popup',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppUsersRoute = AppUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppRoute,
} as any)
const AppUsageRoute = AppUsageRouteImport.update({
  id: '/usage',
  path: '/usage',
  getParentRoute: () => AppRoute,
} as any)
const AppScheduleViewRoute = AppScheduleViewRouteImport.update({
  id: '/schedule-view',
  path: '/schedule-view',
  getParentRoute: () => AppRoute,
} as any)
const AppScheduleRoute = AppScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => AppRoute,
} as any)
const AppSamplesRoute = AppSamplesRouteImport.update({
  id: '/samples',
  path: '/samples',
  getParentRoute: () => AppRoute,
} as any)
const AppMethodsRoute = AppMethodsRouteImport.update({
  id: '/methods',
  path: '/methods',
  getParentRoute: () => AppRoute,
} as any)
const AppInventoryRoute = AppInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AppRoute,
} as any)
const AppImportsRoute = AppImportsRouteImport.update({
  id: '/imports',
  path: '/imports',
  getParentRoute: () => AppRoute,
} as any)
const AppDataRoute = AppDataRouteImport.update({
  id: '/data',
  path: '/data',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/data-popup': typeof DataPopupRoute
  '/login': typeof LoginRoute
  '/analytics': typeof AppAnalyticsRoute
  '/data': typeof AppDataRoute
  '/imports': typeof AppImportsRoute
  '/inventory': typeof AppInventoryRoute
  '/methods': typeof AppMethodsRoute
  '/samples': typeof AppSamplesRoute
  '/schedule': typeof AppScheduleRoute
  '/schedule-view': typeof AppScheduleViewRoute
  '/usage': typeof AppUsageRoute
  '/users': typeof AppUsersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/data-popup': typeof DataPopupRoute
  '/login': typeof LoginRoute
  '/analytics': typeof AppAnalyticsRoute
  '/data': typeof AppDataRoute
  '/imports': typeof AppImportsRoute
  '/inventory': typeof AppInventoryRoute
  '/methods': typeof AppMethodsRoute
  '/samples': typeof AppSamplesRoute
  '/schedule': typeof AppScheduleRoute
  '/schedule-view': typeof AppScheduleViewRoute
  '/usage': typeof AppUsageRoute
  '/users': typeof AppUsersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/data-popup': typeof DataPopupRoute
  '/login': typeof LoginRoute
  '/_app/analytics': typeof AppAnalyticsRoute
  '/_app/data': typeof AppDataRoute
  '/_app/imports': typeof AppImportsRoute
  '/_app/inventory': typeof AppInventoryRoute
  '/_app/methods': typeof AppMethodsRoute
  '/_app/samples': typeof AppSamplesRoute
  '/_app/schedule': typeof AppScheduleRoute
  '/_app/schedule-view': typeof AppScheduleViewRoute
  '/_app/usage': typeof AppUsageRoute
  '/_app/users': typeof AppUsersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/data-popup'
    | '/login'
    | '/analytics'
    | '/data'
    | '/imports'
    | '/inventory'
    | '/methods'
    | '/samples'
    | '/schedule'
    | '/schedule-view'
    | '/usage'
    | '/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/data-popup'
    | '/login'
    | '/analytics'
    | '/data'
    | '/imports'
    | '/inventory'
    | '/methods'
    | '/samples'
    | '/schedule'
    | '/schedule-view'
    | '/usage'
    | '/users'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/data-popup'
    | '/login'
    | '/_app/analytics'
    | '/_app/data'
    | '/_app/imports'
    | '/_app/inventory'
    | '/_app/methods'
    | '/_app/samples'
    | '/_app/schedule'
    | '/_app/schedule-view'
    | '/_app/usage'
    | '/_app/users'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  DataPopupRoute: typeof DataPopupRoute
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data-popup': {
      id: '/data-popup'
      path: '/data-popup'
      fullPath: '/data-popup'
      preLoaderRoute: typeof DataPopupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/users': {
      id: '/_app/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AppUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/usage': {
      id: '/_app/usage'
      path: '/usage'
      fullPath: '/usage'
      preLoaderRoute: typeof AppUsageRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/schedule-view': {
      id: '/_app/schedule-view'
      path: '/schedule-view'
      fullPath: '/schedule-view'
      preLoaderRoute: typeof AppScheduleViewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/schedule': {
      id: '/_app/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof AppScheduleRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/samples': {
      id: '/_app/samples'
      path: '/samples'
      fullPath: '/samples'
      preLoaderRoute: typeof AppSamplesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/methods': {
      id: '/_app/methods'
      path: '/methods'
      fullPath: '/methods'
      preLoaderRoute: typeof AppMethodsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inventory': {
      id: '/_app/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof AppInventoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/imports': {
      id: '/_app/imports'
      path: '/imports'
      fullPath: '/imports'
      preLoaderRoute: typeof AppImportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/data': {
      id: '/_app/data'
      path: '/data'
      fullPath: '/data'
      preLoaderRoute: typeof AppDataRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/analytics': {
      id: '/_app/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppDataRoute: typeof AppDataRoute
  AppImportsRoute: typeof AppImportsRoute
  AppInventoryRoute: typeof AppInventoryRoute
  AppMethodsRoute: typeof AppMethodsRoute
  AppSamplesRoute: typeof AppSamplesRoute
  AppScheduleRoute: typeof AppScheduleRoute
  AppScheduleViewRoute: typeof AppScheduleViewRoute
  AppUsageRoute: typeof AppUsageRoute
  AppUsersRoute: typeof AppUsersRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppDataRoute: AppDataRoute,
  AppImportsRoute: AppImportsRoute,
  AppInventoryRoute: AppInventoryRoute,
  AppMethodsRoute: AppMethodsRoute,
  AppSamplesRoute: AppSamplesRoute,
  AppScheduleRoute: AppScheduleRoute,
  AppScheduleViewRoute: AppScheduleViewRoute,
  AppUsageRoute: AppUsageRoute,
  AppUsersRoute: AppUsersRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  DataPopupRoute: DataPopupRoute,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
